### ISSUE TITLE
Feature request: receiving plain JSON Objects / strings as response

### ISSUE THREAD

**Issue by StephanMeijer** [link0/bunq#17]
I'd like to be abe to receive plain JSON Objects or strings as response instead of the complex response this client returns (maybe you can build in something).

**Comment by dennisdegreef** [comment]
Hi @StephanMeijer 

I think it would be possible to be able to `json_encode` these objects, and if not, implement such behaviour.
Do you have a usecase for this? Why do you prefer plain JSON objects instead of complex types?
The reason the complex types are there, is to assert certain behaviour/structure.

**Comment by StephanMeijer** [comment]
I prefer JSON for the cases where things like `Invoice` are not implemented yet.

**Comment by dennisdegreef** [comment]
Wouldn't it be better to implement `Invoice` in those case? Instead of having to maintain the JSON views as well?

**Comment by StephanMeijer** [comment]
You already receive JSON from the API, so you actually don't have to maintain a thing.

**Comment by dennisdegreef** [comment]
While that is true, why not use the API directly then? Are there some components in this API that might fit better in a separate package? I guess the guzzle middleware might? Please let me know what things you'd like to use from this package while keeping communication JSON based.

**Comment by dennisdegreef** [comment]
Closed due to inactivity. Please feel free to comment on my previous questions.
