### ISSUE TITLE
balance is shown as string in object instead of float

### ISSUE THREAD

**Issue by jerry89899** [link0/bunq#22]
<img width="184" alt="screen shot 2017-05-16 at 18 45 01" src="https://cloud.githubusercontent.com/assets/1766343/26117787/e9004910-3a67-11e7-9fbd-5d8af894d780.png">
Here it shows that the amount of money i have is 29164 which i sadly dont have i only have 291,64.
is there an way to let it show an float?

```php
$monetaryAccountService` = new MonetaryAccountService($client);
$monetaryAccounts = $monetaryAccountService->listByUser($user);
echo json_encode($monetaryAccounts[0]->balance());
```
Here is the noob code i used. haha

**Comment by verschoof** [comment]
The result you got are euro cents. (we don't really like floats :) )

so this will fix your problem:
```
$amount = 29164;

$euro = $amount / 100;
```

http://sandbox.onlinephpfunctions.com/code/190fa1893b934f6cd0e25072ea520d662b078660

**Comment by dennisdegreef** [comment]
Indeed the return value of `balance()` is a Money object, which in serialized form looks like the JSON you pasted. 
With floating point values, you lose precision, while the Money object is designed to avoid just that.
Indeed you can devide by 100 and cast to a float if you like, but since you can chain calls and do calculations with them, I prefer to use the Money object for this.

But thanks for the feedback here :) is your problem solved now?

**Comment by dennisdegreef** [comment]
I have closed the issue, if you have any questions further, feel free to open a new issue. 
Thanks for your question!
